myapp/urls.py
from django.urls import path
from myapp.views import index,PostCreate,detail,like

app_name = 'myapp'

urlpatterns = [
	path('',index,name = 'index'),
	path('create/',PostCreate.as_view(),name = 'create'),
	path('detail/<int:pk>/',detail,name = 'detail'),
	path('ajax/likes',like,name='like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('accounts/', include('registration.backends.default.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True

class Post(TimeStamp):
	title = models.CharField(max_length = 100)
	description = models.TextField()
	image = models.ImageField(upload_to = '')
	likes = models.IntegerField(default = 0)

	def __str__(self):
		return self.title

class Comment(TimeStamp):
	post = models.ForeignKey(Post,on_delete=models.CASCADE)
	comment = models.TextField()

	def __str__(self):
		return self.comment

myapp/forms.py
from django import forms
from myapp.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

myapp/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
import datetime
from myapp.models import Post,Comment
from django.views.generic.edit import CreateView
from myapp.forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
	#process the data
	posts = Post.objects.all()
	context = {'posts':posts}
	return render(request,'index.html',context)

class PostCreate(LoginRequiredMixin,CreateView):
	model = Post
	fields = ['title','description','image']
	template_name = 'create.html'
	success_url = '/'

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super().form_valid(form)

@login_required
def detail(request,pk):
    p = Post.objects.get(pk = pk)
    comments = Comment.objects.filter(post_id = pk)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            comment = form.cleaned_data['comment']
            c = Comment(post_id = pk,comment = comment,user = request.user)
            c.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('myapp:detail', kwargs = {'pk':pk}))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CommentForm()

    return render(request, 'detail.html', {'form': form,'p':p,'comments':comments})

def like(request):
	if request.is_ajax():
		post_id = request.GET.get('post')
		#likes = request.GET.get('likes')
		post = Post.objects.get(id = post_id)
		post.likes += 1
		post.save()
		data = {'likes':post.likes}
	return JsonResponse(data)

myapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>MyApp</title>
	<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'myapp:index' %}">MYAPP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myapp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:create' %}">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="{{request.user}}" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>&nbsp;
    {% if not user.is_authenticated %}
	    <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>&nbsp;
	    <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>
    {% else %}
	    <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>
    {% endif %}
  </div>
</nav>
<div class="container">
	{% block content %}
	<!-- content here -->
	{% endblock %}
</div>
</body>
</html>

myapp/templates/create.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save" class="btn btn-primary">
</form>
{% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="row">
	<div class="col-6">
		{{p.title}}<br>
		{{p.description}}<br>
		<img src="{{p.image.url}}" height="200" width="200"><br>
		created at {{p.created_at}} by {{p.user}}<br>
		updated at: {{p.updated_at}}
	</div>
	<div class="col-6">
		<form action="" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Submit">
		</form>
	</div>
</div>
<p>likes:<span id="like">{{p.likes}}</span></p>
<button onclick="onClick()"><i class="fas fa-thumbs-up"></i></button>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	function onClick() {
		// body...
		var likes = document.getElementById('like').innerHTML;
		$.ajax({
			url:"{% url 'myapp:like' %}",
			data:{'post':{{p.id}}},
			success: function(data){
				//process data
				document.getElementById('like').innerHTML = data.likes
			}
		})

	}
</script>
<div>
	<br>
	<h6>Comments:</h6>
	{% for i in comments %}
		{{forloop.counter}} - {{i.comment}}<br>
		at {{i.created_at}} by {{i.user}}<br>
	{% endfor%}
</div>
{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="row">
{% for i in posts %}
<div class="col-6">
<a href="{% url 'myapp:detail' i.pk %}">{{i.title}}</a><br>
{{i.description}}<br>
<img src="{{i.image.url}}" height="200" width="200"><br>
created at {{i.created_at}} by {{i.user}}<br>
updated at: {{i.updated_at}}
<br><br>
</div>
{% endfor %}
</div>
{% endblock %}